"""Harcownik kickoff

Revision ID: a09784e06775
Revises: 
Create Date: 2023-06-17 23:05:32.723832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a09784e06775'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badge_group'), 'badge', ['group'], unique=False)
    op.create_index(op.f('ix_badge_id'), 'badge', ['id'], unique=False)
    op.create_index(op.f('ix_badge_name'), 'badge', ['name'], unique=False)
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('szczep', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_city'), 'group', ['city'], unique=False)
    op.create_index(op.f('ix_group_id'), 'group', ['id'], unique=False)
    op.create_index(op.f('ix_group_name'), 'group', ['name'], unique=False)
    op.create_index(op.f('ix_group_number'), 'group', ['number'], unique=False)
    op.create_index(op.f('ix_group_szczep'), 'group', ['szczep'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('function', sa.String(), nullable=False),
    sa.Column('is_teamadmin', sa.Boolean(), nullable=True),
    sa.Column('is_webadmin', sa.Boolean(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_function'), 'user', ['function'], unique=False)
    op.create_index(op.f('ix_user_hashed_password'), 'user', ['hashed_password'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_is_teamadmin'), 'user', ['is_teamadmin'], unique=False)
    op.create_index(op.f('ix_user_is_webadmin'), 'user', ['is_webadmin'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_level'), 'user', ['level'], unique=False)
    op.create_table('badge_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('badge_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badge.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badge_report_id'), 'badge_report', ['id'], unique=False)
    op.create_index(op.f('ix_badge_report_status'), 'badge_report', ['status'], unique=False)
    op.create_index(op.f('ix_badge_report_title'), 'badge_report', ['title'], unique=False)
    op.create_table('level_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_level_report_id'), 'level_report', ['id'], unique=False)
    op.create_index(op.f('ix_level_report_status'), 'level_report', ['status'], unique=False)
    op.create_index(op.f('ix_level_report_title'), 'level_report', ['title'], unique=False)
    op.create_table('reports_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_history_id'), 'reports_history', ['id'], unique=False)
    op.create_index(op.f('ix_reports_history_name'), 'reports_history', ['name'], unique=False)
    op.create_table('user_badges',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('badge_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badge.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_reports_history_name'), table_name='reports_history')
    op.drop_index(op.f('ix_reports_history_id'), table_name='reports_history')
    op.drop_table('reports_history')
    op.drop_index(op.f('ix_level_report_title'), table_name='level_report')
    op.drop_index(op.f('ix_level_report_status'), table_name='level_report')
    op.drop_index(op.f('ix_level_report_id'), table_name='level_report')
    op.drop_table('level_report')
    op.drop_index(op.f('ix_badge_report_title'), table_name='badge_report')
    op.drop_index(op.f('ix_badge_report_status'), table_name='badge_report')
    op.drop_index(op.f('ix_badge_report_id'), table_name='badge_report')
    op.drop_table('badge_report')
    op.drop_index(op.f('ix_user_level'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_is_webadmin'), table_name='user')
    op.drop_index(op.f('ix_user_is_teamadmin'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_hashed_password'), table_name='user')
    op.drop_index(op.f('ix_user_function'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_group_szczep'), table_name='group')
    op.drop_index(op.f('ix_group_number'), table_name='group')
    op.drop_index(op.f('ix_group_name'), table_name='group')
    op.drop_index(op.f('ix_group_id'), table_name='group')
    op.drop_index(op.f('ix_group_city'), table_name='group')
    op.drop_table('group')
    op.drop_index(op.f('ix_badge_name'), table_name='badge')
    op.drop_index(op.f('ix_badge_id'), table_name='badge')
    op.drop_index(op.f('ix_badge_group'), table_name='badge')
    op.drop_table('badge')
    # ### end Alembic commands ###
