"""ScienceClub

Revision ID: bb347da8c21b
Revises: 60df8e1803e2
Create Date: 2024-01-11 20:35:50.271327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb347da8c21b'
down_revision = '60df8e1803e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_level', table_name='user')
    op.drop_column('user', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_user_level', 'user', ['level'], unique=False)
    # ### end Alembic commands ###
